In [4]:
import pandas as pd

In [11]:
df1 = pd.read_csv('/home/Danny/AI-CUP-2020/datasets/stage1/SampleData_deid.csv')
df1

,text,article_id,start_position,end_position,entity_text,entity_type
0,醫師：你有做超音波嘛，那我們來看報告，有些部分有紅字耶。民眾：紅字是甚麼意思？醫師：就是肝功...,0,55,57,68,med_exam
1,醫師：你有做超音波嘛，那我們來看報告，有些部分有紅字耶。民眾：紅字是甚麼意思？醫師：就是肝功...,0,66,68,68,med_exam
2,醫師：你有做超音波嘛，那我們來看報告，有些部分有紅字耶。民眾：紅字是甚麼意思？醫師：就是肝功...,0,1264,1271,10.78公分,med_exam
3,醫師：你有做超音波嘛，那我們來看報告，有些部分有紅字耶。民眾：紅字是甚麼意思？醫師：就是肝功...,0,1358,1361,三多路,location
4,醫師：你有做超音波嘛，那我們來看報告，有些部分有紅字耶。民眾：紅字是甚麼意思？醫師：就是肝功...,0,1374,1378,長庚醫院,location
...,...,...,...,...,...,...
441,醫師：好，所以，這個月還好嗎？民眾：還OK。醫師：還可以。民眾：嗯。醫師：那……你吃任務型嘛...,25,467,470,兩年多,time
442,醫師：好，所以，這個月還好嗎？民眾：還OK。醫師：還可以。民眾：嗯。醫師：那……你吃任務型嘛...,25,1396,1400,第四個月,time
443,醫師：好，所以，這個月還好嗎？民眾：還OK。醫師：還可以。民眾：嗯。醫師：那……你吃任務型嘛...,25,1451,1456,5月30號,time
444,醫師：好，所以，這個月還好嗎？民眾：還OK。醫師：還可以。民眾：嗯。醫師：那……你吃任務型嘛...,25,1499,1501,千尋,name
445,醫師：好，所以，這個月還好嗎？民眾：還OK。醫師：還可以。民眾：嗯。醫師：那……你吃任務型嘛...,25,1580,1584,第四個月,time

In [12]:
df2 = pd.read_csv('/home/Danny/AI-CUP-2020/datasets/stage2/train_1_update.csv')
df2

,text,article_id,start_position,end_position,entity_text,entity_type
0,醫師：啊回去還好嗎？民眾：欸，還是虛虛的，但。醫師：欸，真的。民眾：好險好險。坦白講我剛回去...,0,69,71,前天,time
1,醫師：啊回去還好嗎？民眾：欸，還是虛虛的，但。醫師：欸，真的。民眾：好險好險。坦白講我剛回去...,0,75,77,前天,time
2,醫師：啊回去還好嗎？民眾：欸，還是虛虛的，但。醫師：欸，真的。民眾：好險好險。坦白講我剛回去...,0,738,740,85,med_exam
3,醫師：啊回去還好嗎？民眾：欸，還是虛虛的，但。醫師：欸，真的。民眾：好險好險。坦白講我剛回去...,0,741,744,102,med_exam
4,醫師：啊回去還好嗎？民眾：欸，還是虛虛的，但。醫師：欸，真的。民眾：好險好險。坦白講我剛回去...,0,809,811,前年,time
...,...,...,...,...,...,...
2131,醫師：那所以你現在藥是有繼續在吃？民眾：有。醫師：那比方說像是過去這個月你有性行為嗎？民眾：...,119,1136,1138,彰化,location
2132,醫師：那所以你現在藥是有繼續在吃？民眾：有。醫師：那比方說像是過去這個月你有性行為嗎？民眾：...,119,1143,1145,彰化,location
2133,醫師：那所以你現在藥是有繼續在吃？民眾：有。醫師：那比方說像是過去這個月你有性行為嗎？民眾：...,119,1173,1177,彰化醫院,location
2134,醫師：那所以你現在藥是有繼續在吃？民眾：有。醫師：那比方說像是過去這個月你有性行為嗎？民眾：...,119,1216,1221,陳明明醫師,name
2135,醫師：那所以你現在藥是有繼續在吃？民眾：有。醫師：那比方說像是過去這個月你有性行為嗎？民眾：...,119,1250,1255,陳明明醫師,name

In [14]:
df4 = pd.read_csv('/home/Danny/AI-CUP-2020/datasets/stage4/train_2.csv')
df4

,text,article_id,start_position,end_position,entity_text,entity_type
0,醫師：啊回去還好嗎？民眾：欸，還是虛虛的，但。醫師：欸，真的。民眾：好險好險。坦白講我剛回去...,0,69,71,前天,time
1,醫師：啊回去還好嗎？民眾：欸，還是虛虛的，但。醫師：欸，真的。民眾：好險好險。坦白講我剛回去...,0,75,77,前天,time
2,醫師：啊回去還好嗎？民眾：欸，還是虛虛的，但。醫師：欸，真的。民眾：好險好險。坦白講我剛回去...,0,738,740,85,med_exam
3,醫師：啊回去還好嗎？民眾：欸，還是虛虛的，但。醫師：欸，真的。民眾：好險好險。坦白講我剛回去...,0,741,744,102,med_exam
4,醫師：啊回去還好嗎？民眾：欸，還是虛虛的，但。醫師：欸，真的。民眾：好險好險。坦白講我剛回去...,0,809,811,前年,time
...,...,...,...,...,...,...
3826,醫師：你那個膿還是會痛？民眾：對。醫師：發炎指數很好。民眾：多少？醫師：1.7，1.7正常，...,199,36,39,1.7,med_exam
3827,醫師：你那個膿還是會痛？民眾：對。醫師：發炎指數很好。民眾：多少？醫師：1.7，1.7正常，...,199,40,43,1.7,med_exam
3828,醫師：你那個膿還是會痛？民眾：對。醫師：發炎指數很好。民眾：多少？醫師：1.7，1.7正常，...,199,48,51,9.0,med_exam
3829,醫師：你那個膿還是會痛？民眾：對。醫師：發炎指數很好。民眾：多少？醫師：1.7，1.7正常，...,199,53,56,1.7,med_exam
3830,醫師：你那個膿還是會痛？民眾：對。醫師：發炎指數很好。民眾：多少？醫師：1.7，1.7正常，...,199,1065,1067,小美,name

In [44]:
df = df1.append(df2).append(df4)
df

,text,article_id,start_position,end_position,entity_text,entity_type
0,醫師：你有做超音波嘛，那我們來看報告，有些部分有紅字耶。民眾：紅字是甚麼意思？醫師：就是肝功...,0,55,57,68,med_exam
1,醫師：你有做超音波嘛，那我們來看報告，有些部分有紅字耶。民眾：紅字是甚麼意思？醫師：就是肝功...,0,66,68,68,med_exam
2,醫師：你有做超音波嘛，那我們來看報告，有些部分有紅字耶。民眾：紅字是甚麼意思？醫師：就是肝功...,0,1264,1271,10.78公分,med_exam
3,醫師：你有做超音波嘛，那我們來看報告，有些部分有紅字耶。民眾：紅字是甚麼意思？醫師：就是肝功...,0,1358,1361,三多路,location
4,醫師：你有做超音波嘛，那我們來看報告，有些部分有紅字耶。民眾：紅字是甚麼意思？醫師：就是肝功...,0,1374,1378,長庚醫院,location
...,...,...,...,...,...,...
3826,醫師：你那個膿還是會痛？民眾：對。醫師：發炎指數很好。民眾：多少？醫師：1.7，1.7正常，...,199,36,39,1.7,med_exam
3827,醫師：你那個膿還是會痛？民眾：對。醫師：發炎指數很好。民眾：多少？醫師：1.7，1.7正常，...,199,40,43,1.7,med_exam
3828,醫師：你那個膿還是會痛？民眾：對。醫師：發炎指數很好。民眾：多少？醫師：1.7，1.7正常，...,199,48,51,9.0,med_exam
3829,醫師：你那個膿還是會痛？民眾：對。醫師：發炎指數很好。民眾：多少？醫師：1.7，1.7正常，...,199,53,56,1.7,med_exam
3830,醫師：你那個膿還是會痛？民眾：對。醫師：發炎指數很好。民眾：多少？醫師：1.7，1.7正常，...,199,1065,1067,小美,name

In [46]:
df = df[['entity_text', 'entity_type']]
df

     entity_text entity_type
0             68    med_exam
1             68    med_exam
2        10.78公分    med_exam
3            三多路    location
4           長庚醫院    location
...          ...         ...
3826         1.7    med_exam
3827         1.7    med_exam
3828         9.0    med_exam
3829         1.7    med_exam
3830          小美        name

[6413 rows x 2 columns]

In [47]:
pd.unique(df['entity_type'])

array(['med_exam', 'location', 'time', 'profession', 'name', 'money',
       'organization', 'family', 'ID', 'clinical_event', 'education',
       'contact', 'others'], dtype=object)

In [51]:
med_exam = df[df['entity_type'] == 'med_exam']
med_exam.to_csv('data/med_exam.csv', index=False)

In [52]:
location = df[df['entity_type'] == 'location']
location.to_csv('data/location.csv', index=False)

In [53]:
time = df[df['entity_type'] == 'time']
time.to_csv('data/time.csv', index=False)

In [54]:
profession = df[df['entity_type'] == 'profession']
profession.to_csv('data/profession.csv', index=False)

In [55]:
name = df[df['entity_type'] == 'name']
name.to_csv('data/name.csv', index=False)

In [56]:
money = df[df['entity_type'] == 'money']
money.to_csv('data/money.csv', index=False)

In [57]:
organization = df[df['entity_type'] == 'organization']
organization.to_csv('data/organization.csv', index=False)

In [58]:
family = df[df['entity_type'] == 'family']
family.to_csv('data/family.csv', index=False)

In [59]:
ID = df[df['entity_type'] == 'ID']
ID.to_csv('data/ID.csv', index=False)

In [60]:
clinical_event = df[df['entity_type'] == 'clinical_event']
clinical_event.to_csv('data/clinical_event.csv', index=False)

In [61]:
education = df[df['entity_type'] == 'education']
education.to_csv('data/education.csv', index=False)

In [62]:
contact = df[df['entity_type'] == 'contact']
contact.to_csv('data/contact.csv', index=False)

In [63]:
others = df[df['entity_type'] == 'others']
others.to_csv('data/others.csv', index=False)